name: GitHub Pages Deployment Workflow

on:
  workflow_run:
    workflows: ["SAST and CI Pipeline for Portfolio"]
    types: [completed]

jobs:
  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      contents: write # push to gh-pages
      pages: write # deploy to GitHub Pages
      id-token: write # authentication with GitHub Pages
      actions: read # read actions

    steps:
      #   - name: Install GitHub CLI
      #     run: sudo apt-get install -y gh

      # https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories
      - name: Download artifact from triggering workflow
        uses: actions/download-artifact@v5
        with:
          name: dist
          path: ./dist
          github-token: ${{ github.token }} # if the workflow in the same repository, use the default token
          run-id: ${{ github.event.workflow_run.id }} # Use the run ID from the triggering workflow
        # env:
        #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Verify artifact contents
      - name: Verify artifact contents
        run: |
          echo "Downloaded artifact contents:"
          ls -la 
          cd dist
          ls -la

      # 4. Add custom CNAME for GitHub Pages
      - name: Set up CNAME for GitHub Pages
        run: |
          echo "www.pavanclouds.com" > ./dist/CNAME

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages with custom domain
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
